export interface WeatherCodeInfo {
  code: number;
  label: string;
  category: 'clear' | 'cloudy' | 'fog' | 'drizzle' | 'rain' | 'snow' | 'thunderstorm';
  iconName: string;
  bgGradientDay: string;
  bgGradientNight: string;
  textColor: string;
}

export const WEATHER_CODES: Record<number, WeatherCodeInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    category: 'clear',
    iconName: 'Sun',
    bgGradientDay: 'from-amber-400 via-sky-400 to-blue-500',
    bgGradientNight: 'from-indigo-950 via-slate-900 to-blue-950',
    textColor: 'text-amber-500',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    category: 'clear',
    iconName: 'SunDim',
    bgGradientDay: 'from-sky-400 via-blue-400 to-indigo-500',
    bgGradientNight: 'from-slate-900 via-indigo-950 to-blue-900',
    textColor: 'text-amber-400',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    category: 'cloudy',
    iconName: 'CloudSun',
    bgGradientDay: 'from-blue-400 via-sky-300 to-slate-400',
    bgGradientNight: 'from-slate-900 via-blue-950 to-slate-800',
    textColor: 'text-sky-400',
  },
  3: {
    code: 3,
    label: 'Overcast',
    category: 'cloudy',
    iconName: 'Cloud',
    bgGradientDay: 'from-slate-500 via-slate-400 to-zinc-500',
    bgGradientNight: 'from-zinc-900 via-slate-900 to-neutral-900',
    textColor: 'text-slate-400',
  },
  45: {
    code: 45,
    label: 'Foggy',
    category: 'fog',
    iconName: 'CloudFog',
    bgGradientDay: 'from-slate-400 via-zinc-400 to-slate-500',
    bgGradientNight: 'from-zinc-950 via-slate-900 to-zinc-900',
    textColor: 'text-slate-300',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    category: 'fog',
    iconName: 'CloudFog',
    bgGradientDay: 'from-slate-400 via-sky-200 to-zinc-400',
    bgGradientNight: 'from-slate-950 via-zinc-900 to-slate-900',
    textColor: 'text-sky-300',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    category: 'drizzle',
    iconName: 'CloudDrizzle',
    bgGradientDay: 'from-sky-500 via-slate-400 to-blue-600',
    bgGradientNight: 'from-slate-950 via-blue-950 to-zinc-900',
    textColor: 'text-sky-400',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    category: 'drizzle',
    iconName: 'CloudDrizzle',
    bgGradientDay: 'from-sky-600 via-slate-500 to-blue-700',
    bgGradientNight: 'from-slate-950 via-blue-950 to-slate-900',
    textColor: 'text-sky-300',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    category: 'drizzle',
    iconName: 'CloudDrizzle',
    bgGradientDay: 'from-blue-600 via-slate-600 to-indigo-700',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-slate-900',
    textColor: 'text-blue-400',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    category: 'rain',
    iconName: 'CloudRain',
    bgGradientDay: 'from-blue-500 via-sky-600 to-slate-700',
    bgGradientNight: 'from-slate-950 via-blue-950 to-indigo-950',
    textColor: 'text-blue-400',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    category: 'rain',
    iconName: 'CloudRain',
    bgGradientDay: 'from-blue-600 via-indigo-700 to-slate-800',
    bgGradientNight: 'from-slate-950 via-blue-950 to-slate-900',
    textColor: 'text-blue-300',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    category: 'rain',
    iconName: 'CloudRainWind',
    bgGradientDay: 'from-blue-700 via-indigo-800 to-slate-900',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-slate-950',
    textColor: 'text-blue-200',
  },
  71: {
    code: 71,
    label: 'Slight Snow Fall',
    category: 'snow',
    iconName: 'CloudSnow',
    bgGradientDay: 'from-sky-300 via-blue-200 to-slate-400',
    bgGradientNight: 'from-slate-900 via-blue-950 to-sky-950',
    textColor: 'text-sky-200',
  },
  73: {
    code: 73,
    label: 'Moderate Snow Fall',
    category: 'snow',
    iconName: 'CloudSnow',
    bgGradientDay: 'from-sky-200 via-indigo-300 to-slate-400',
    bgGradientNight: 'from-slate-900 via-sky-950 to-indigo-950',
    textColor: 'text-sky-100',
  },
  75: {
    code: 75,
    label: 'Heavy Snow Fall',
    category: 'snow',
    iconName: 'Snowflake',
    bgGradientDay: 'from-slate-200 via-sky-200 to-blue-300',
    bgGradientNight: 'from-slate-950 via-blue-950 to-slate-900',
    textColor: 'text-white',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    category: 'rain',
    iconName: 'CloudSunRain',
    bgGradientDay: 'from-sky-400 via-blue-500 to-slate-600',
    bgGradientNight: 'from-slate-900 via-blue-950 to-zinc-900',
    textColor: 'text-sky-300',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    category: 'rain',
    iconName: 'CloudRain',
    bgGradientDay: 'from-blue-500 via-indigo-600 to-slate-700',
    bgGradientNight: 'from-slate-950 via-blue-950 to-slate-900',
    textColor: 'text-blue-300',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    category: 'rain',
    iconName: 'CloudRainWind',
    bgGradientDay: 'from-blue-700 via-indigo-800 to-slate-900',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-zinc-950',
    textColor: 'text-blue-200',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    category: 'thunderstorm',
    iconName: 'CloudLightning',
    bgGradientDay: 'from-purple-900 via-slate-800 to-indigo-950',
    bgGradientNight: 'from-slate-950 via-purple-950 to-zinc-950',
    textColor: 'text-amber-300',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Slight Hail',
    category: 'thunderstorm',
    iconName: 'CloudHail',
    bgGradientDay: 'from-indigo-900 via-purple-950 to-slate-900',
    bgGradientNight: 'from-slate-950 via-purple-950 to-indigo-950',
    textColor: 'text-amber-200',
  },
  99: {
    code: 99,
    label: 'Thunderstorm with Heavy Hail',
    category: 'thunderstorm',
    iconName: 'CloudHail',
    bgGradientDay: 'from-purple-950 via-slate-950 to-indigo-950',
    bgGradientNight: 'from-slate-950 via-zinc-950 to-purple-950',
    textColor: 'text-amber-400',
  },
};

export function getWeatherCodeInfo(code: number): WeatherCodeInfo {
  return (
    WEATHER_CODES[code] || {
      code,
      label: 'Weather Condition',
      category: 'cloudy',
      iconName: 'Cloud',
      bgGradientDay: 'from-blue-400 via-sky-300 to-slate-400',
      bgGradientNight: 'from-slate-900 via-blue-950 to-slate-800',
      textColor: 'text-sky-400',
    }
  );
}
